services:
  - type: web
    name: vote-yussuf-website
    env: static
    buildCommand: echo "No build step required"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /*
        name: Permissions-Policy
        value: geolocation=(), microphone=(), camera=()
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000
    domains:
      - voteyussuf.com
      - www.voteyussuf.com